server {
    listen 80;
    server_name localhost;
    root /var/www/backend/public;
    index index.php;

    client_max_body_size 64M;

    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass geplan_app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location /build/ {
        root /var/www/frontend/dist;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location / {
        root /var/www/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.ht { deny all; }
    location ~ /\.env { deny all; }
}
